### PR TITLE
Update for 4.x

### PR DESCRIPTION
**Pull request by Ash-86**
Added a block in component.On complete to make the pulgin work in musescore 4.x

### CODE REVIEW

**Comment by ecstrema** [comment]
Thank you for the PR.

> Added a block in component.On complete to make the pulgin work in musescore 4.x

I don't see any onComplete hook though. Did you forget to push your latest changes?

The thumbnailName is an inexisting .png file. Is it one you planned on providing?

Is there any documentation for these 2 new properties (categoryCode, thumbnailName)?

**Comment by Ash-86** [comment]
It´s in line 41 to 45. an if statement to check if version of musescore is >4.

I added a png image and changed the thumbnailName to match.

**Comment by ecstrema** [comment]
Nice. I love the thumbnail:)

**Comment by Ash-86** [comment]
Cheers! The plugin is very helpful. Though it seems like you have to make sure there are no duplicate shrotcuts with musescore's, otherwise thy won't work. Btw, I think it is interesting if the undo action, somehow, undoes the last chain action, and not only the individual steps. Thanks for the Plugin!

**Pull request merged**
